[tool.poetry]
name = "simple_test_process"
version = "0.2.0"
description = "The process ran by simple_test to isolate the environment"
authors = ["Philip Olson <philip.olson@pm.me>"]
license = "WTFNMFPL-1.0"
readme = "README.md"
repository = "https://github.com/olsonpm/py_simple-test-process"
include = ["license.txt"]

[tool.poetry.dependencies]
python = "^3.7"
toml = "^0.10.0"
case_conversion = "^2.1"
simple_chalk = "^0.1.0"
wrapt = "^1.10"
ordered_set = "^3.1"
num2words = "^0.5.8"
tedent = "^0.1.1"
pretty_simple_namespace = "^0.1.0"

[tool.poetry.dev-dependencies]
toml = "^0.10.0"
is_git_repo_clean = "^0.3.4"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
