[tool.poetry]
name = "artworks"
version = "0.1.0"
description = ""
authors = ["castaneai <castaneai@castaneai.net>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6"
mutagen = "^1.42"

[tool.poetry.dev-dependencies]
pytest = "^4.3"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
