[tool.poetry]
name = "flask-dramatiq"
version = "0.2.0"
description = "Adds Dramatiq support to your Flask application"
authors = ["Ã‰tienne BERSAC"]
license = "BSD-3-Clause"
readme = "README.md"
homepage = "https://pypi.org/project/flask-dramatiq"

[tool.poetry.dependencies]
python = "^3.6"
dramatiq = "^1.5"
flask-migrate = "^2.4"

[tool.poetry.dev-dependencies]
flake8 = "^3.7"
flask-sqlalchemy = "^2.3"
dramatiq = {version = "^1.5",extras = ["rabbitmq"]}
psycopg2 = "^2.7"
flask-migrate = "^2.4"
pytest = "^4.3"
requests = "^2.21"

[tool.poetry.plugins."flask.commands"]
worker = "flask_dramatiq:worker"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
